export const colleges = [
    {
      rank: 1,
      name: 'IIT Madras',
      course: 'B.Tech Computer Science Engineering',
      fees: 209550,
      rating: 8.6,
      reviews: 8.6,
      reviewsCount: 297,
      featured: false,
      placement: {
        average: 2148000,
        highest: 1980000,
      },
      ranking: 3,
    },
    {
      rank: 2,
      name: 'IIT Delhi',
      course: 'B.Tech Mathematics and Computing',
      fees: 254650,
      rating: 8.7,
      reviews: 8.7,
      reviewsCount: 415,
      featured: false,
      placement: {
        average: 2582000,
        highest: 2000000,
      },
      ranking: 1,
    },
    {
      rank: 3,
      name: 'Parul University, Vadodara',
      course: 'B.Tech',
      fees: 149000,
      rating: 8.1,
      reviews: 8.1,
      reviewsCount: 892,
      featured: true,
      placement: {
        average: 400000,
        highest: 300000,
      },
      ranking: 197,
    },
    {
      rank: 4,
      name: 'IIT Bombay',
      course: 'B.Tech Computer Science Engineering',
      fees: 229300,
      rating: 8.8,
      reviews: 8.8,
      reviewsCount: 306,
      featured: false,
      placement: {
        average: 2182000,
        highest: 3670000,
      },
      ranking: 2,
    },
    {
      rank: 5,
      name: 'IIT Kanpur',
      course: 'B.Tech Aerospace Engineering',
      fees: 200000,
      rating: 8.5,
      reviews: 8.5,
      reviewsCount: 250,
      featured: false,
      placement: {
        average: 2200000,
        highest: 1800000,
      },
      ranking: 5,
    },
    {
      rank: 6,
      name: 'NIT Trichy',
      course: 'B.Tech Civil Engineering',
      fees: 165000,
      rating: 8.3,
      reviews: 8.3,
      reviewsCount: 430,
      featured: false,
      placement: {
        average: 1400000,
        highest: 1600000,
      },
      ranking: 10,
    },
    {
      rank: 7,
      name: 'BITS Pilani',
      course: 'B.Tech Electrical and Electronics Engineering',
      fees: 350000,
      rating: 8.9,
      reviews: 8.9,
      reviewsCount: 500,
      featured: true,
      placement: {
        average: 3000000,
        highest: 2200000,
      },
      ranking: 4,
    },
    {
      rank: 8,
      name: 'VIT Vellore',
      course: 'B.Tech Mechanical Engineering',
      fees: 175000,
      rating: 7.9,
      reviews: 7.9,
      reviewsCount: 600,
      featured: false,
      placement: {
        average: 1200000,
        highest: 1500000,
      },
      ranking: 15,
    },
    {
      rank: 9,
      name: 'SRM University, Chennai',
      course: 'B.Tech Information Technology',
      fees: 200000,
      rating: 8.0,
      reviews: 8.0,
      reviewsCount: 550,
      featured: false,
      placement: {
        average: 1600000,
        highest: 1900000,
      },
      ranking: 12,
    },
    {
      rank: 10,
      name: 'Manipal Institute of Technology',
      course: 'B.Tech Electronics and Communication Engineering',
      fees: 250000,
      rating: 8.4,
      reviews: 8.4,
      reviewsCount: 350,
      featured: true,
      placement: {
        average: 1800000,
        highest: 2000000,
      },
      ranking: 8,
    },
  ];
  